# generated by clj2nix
{ fetchMavenArtifact, fetchgit }:
  let repos = [
        "https://repo.clojars.org/"
        "https://repo1.maven.org/"
        "http://central.maven.org/maven2/"
        "http://oss.sonatype.org/content/repositories/releases/"
        "http://oss.sonatype.org/content/repositories/public/"
        "http://repo.typesafe.com/typesafe/releases/"
      ];
  in rec {
      makePaths = {extraClasspaths ? []}: (builtins.map (dep: if builtins.hasAttr "jar" dep.path then dep.path.jar else dep.path) packages) ++ extraClasspaths;
      makeClasspaths = {extraClasspaths ? []}: builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});

      packages = [
  {
    name = "clj-time";
    path = fetchMavenArtifact {
      inherit repos;
      artifactId = "clj-time";
      groupId = "clj-time";
      sha512 = "b8012a4b1d9de72d3d1fe5b96dd5c36900f2a9aa040c76727f8ab7b744c1b0c758af17ac46075ac82d8e549a22c018e7d20b5aec4c774764508d28ab66f4a1f7";
      version = "0.14.2";
    };
  }

  {
    name = "org.clojure/data.csv";
    path = fetchgit {
      name = "data.csv";
      url = "https://github.com/clojure/data.csv.git";
      rev = "e5beccad0bafdb8e78f19cba481d4ecef5fabf36";
      sha256 = "021yhc19biycrdcyfak2hyy6jncrw3fhkqzd1jr77rid3f54nqx0";
    };
  }

  {
    name = "joda-time/joda-time";
    path = fetchMavenArtifact {
      inherit repos;
      artifactId = "joda-time";
      groupId = "joda-time";
      sha512 = "e1763df430f9b2556c591ab894668231a2d74ce946f4c6d460630272b55b02166c40715fdd7eab983cd4247fee19d48a23141d82aa17fc9c7ef6053f3b7bea80";
      version = "2.9.7";
    };
  }

  ];
  }
  